version: '3'

services:
  db:
    image: postgres
  web:
    build: 
      context: .
      dockerfile: docker/backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - dev.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
